export enum ExceptionNameToCode {
  BadRequestException = 400,
  UnauthorizedException = 401,
  ForbiddenException = 403,
  NotFoundException = 404,
  MethodNotAllowedException = 405,
  NotAcceptableException = 406,
  RequestTimeoutException = 408,
  ConflictException = 409,
  GoneException = 410,
  PreconditionFailedException = 412,
  PayloadTooLargeException = 413,
  UnsupportedMediaTypeException = 415,
  MisdirectedException = 421,
  UnprocessableEntityException = 422,
  InternalServerErrorException = 500,
  NotImplementedException = 501,
  BadGatewayException = 502,
  ServiceUnavailableException = 503,
  GatewayTimeoutException = 504,
  HttpVersionNotSupportedException = 505,
}
